version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    volumes:
      - ./api-gateway:/usr/src/app  
    ports:
      - "5000:5000"
    networks:
      - microservice

  db_user-service:
    container_name: db_user-service
    image: postgres:13
    restart: always
    env_file:
      - ./user-service/.env
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: FB1atQfXCPptY7I7BuMsAX91bGcTXx4R
      POSTGRES_DB: db_user-service
    ports:
      - "3801:5432"
    networks:
      - microservice

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    volumes:
      - ./user-service:/usr/src/app  
    ports:
      - "5001:5001"
    networks:
      - microservice
    depends_on:
      - db_user-service  
    command: ["./wait-for-it.sh", "db_user-service", "--", "node", "./src/app.js"]

  db_product-service:
    container_name: db_product-service
    image: postgres:13
    restart: always
    env_file:
      - ./product-service/.env
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: FB1atQfXCPptY7I7BuMsAX91bGcTXx4R
      POSTGRES_DB: db_product-service
    ports:
      - "3802:5433"
    networks:
      - microservice

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    env_file:
      - ./product-service/.env
    volumes:
      - ./product-service:/usr/src/app  
    ports:
      - "5002:5002"
    networks:
      - microservice
    depends_on:
      - db_product-service  
    command: ["./wait-for-it.sh", "db_product-service", "--", "node", "./src/app.js"]


  db_transaction-history-service:
    container_name: db_transaction-history-service
    image: postgres:13
    restart: always
    env_file:
      - ./transaction-history-service/.env
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: FB1atQfXCPptY7I7BuMsAX91bGcTXx4R
      POSTGRES_DB: db_transaction-history-service
    ports:
      - "3803:5434"
    networks:
      - microservice

  transaction-history-service:
    build:
      context: ./transaction-history-service
    container_name: transaction-history-service
    env_file:
      - ./transaction-history-service/.env
    volumes:
      - ./transaction-history-service:/usr/src/app  
    ports:
      - "5003:5003"
    networks:
      - microservice
    depends_on:
      - db_transaction-history-service 
    command: ["./wait-for-it.sh", "db_transaction-history-service", "--", "node", "./src/app.js"]


networks:
  microservice:
    driver: bridge
    external: true