services:
  angular:
    container_name: angular
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - .:/usr/src/app  
    restart: always

networks:
  microservice:
    driver: bridge
    external: true